# Generated by Django 4.1.3 on 2022-11-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
    ]
