# Generated by Django 4.1.3 on 2022-11-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0005_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Chat',
        ),
    ]
