# Generated by Django 4.1.3 on 2022-11-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0006_rename_group_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='imessage.chat'),
        ),
    ]
