# Generated by Django 4.1.3 on 2022-11-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0008_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
