# Generated by Django 4.1.3 on 2022-12-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0011_alter_message_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
