# Generated by Django 4.1.3 on 2022-12-05 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0014_rename_requester_friendrequests_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequests',
            name='requestedUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
