# Generated by Django 4.1.3 on 2022-12-05 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0015_friendrequests_requesteduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequests',
            new_name='FriendRequest',
        ),
    ]
