# Generated by Django 4.1.3 on 2022-12-11 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0016_rename_friendrequests_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
